
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hire_inn_labs_development
  username: rails
  password: password
  host: localhost







test:
  <<: *default
  database: hire_inn_labs_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
